services:
  - type: web
    name: calendar-sms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: calendar-db
          property: connectionString

  - type: worker
    name: reminder-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py process_reminders --interval 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: calendar-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: PYTHONUNBUFFERED
        value: 1
      - key: RENDER
        value: true

databases:
  - name: calendar-db
    databaseName: calendar
    user: calendar_user
