# Generated by Django 5.1.6 on 2025-02-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_uri', models.TextField(blank=True, null=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('client_secret', models.TextField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('original_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free Plan'), ('starter', 'Starter Plan'), ('pro', 'Pro Plan'), ('business', 'Business Plan')], default='free', max_length=20)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('trial_start_date', models.DateTimeField(blank=True, null=True)),
                ('meetings_this_month', models.IntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_credentials', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.userprofile')),
            ],
        ),
    ]
