# Generated by Django 4.2.17 on 2025-02-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='googlecredentials',
            name='created_at',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Virtual Meeting', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.CharField(default='Untitled Event', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='client_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='client_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='scopes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='token_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('pro', '')], max_length=10),
        ),
    ]
