# Generated by Django 4.2.17 on 2025-04-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_guest_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='setup_stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free Plan'), ('STARTER', 'Starter Plan'), ('PRO', 'Pro Plan'), ('BUSINESS', 'Business Plan')], default='FREE', max_length=20),
        ),
    ]
