# Generated by Django 4.2.17 on 2025-04-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_userprofile_is_guest_mode_userprofile_setup_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='needs_sync',
            field=models.BooleanField(default=False),
        ),
    ]
