# Generated by Django 4.2.17 on 2025-04-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_event_needs_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_reminder_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('reminder', 'Event Reminder')], max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('data', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.event')),
            ],
        ),
    ]
