# Generated by Django 4.2.17 on 2025-02-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_event_location_alter_event_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meetings_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('starter', 'Starter Plan'), ('pro', ''), ('business', 'Business Plan')], default='free', max_length=20),
        ),
    ]
