# Generated by Django 4.2.17 on 2025-02-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_userprofile_meetings_this_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('starter', 'Starter Plan'), ('pro', 'Pro Plan'), ('business', 'Business Plan')], default='free', max_length=20),
        ),
    ]
