# Generated by Django 4.2.17 on 2025-02-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_shortlink_original_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='original_url',
            field=models.TextField(),
        ),
    ]
